inputs:
  exp_file: "data/DEG.AtGenExpress.signed_zstats.heat_shoots"
  seed_file: "data/DEG.AtGenExpress.signed_binary.heat_shoots"
  tf_li_file: "data/Ath_TF_list.gene"
  ppi_file: "data/PPI_Ara.tsv"
  result_dir: "result/GSE5621/"
  grn_file: "data/templateNetwork"
  kegg_dir: "data/kegg_ath_gene.txt"

parameters:
  nThreads: 20
  nTimePoints: 6
  prefix: "PropaNet"
  nReplicates: 2
  
  reg_kernel: 0.2
  corr_thr: 0.5
  edge_thr: 0.5
  nComp: 15
  norm: True